CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `login` varchar(30) NOT NULL,
  `password` varchar(50) NOT NULL,
  `mail` varchar(50) NOT NULL,
  `skill` float(9,3) unsigned NOT NULL DEFAULT '0.000',
  `date_register` datetime NOT NULL,
  `date_activate` datetime DEFAULT NULL,
  `date_comment_last` datetime DEFAULT NULL,
  `ip_register` varchar(20) NOT NULL,
  `rating` float(9,3) NOT NULL DEFAULT '0.000',
  `count_vote` int(11) unsigned NOT NULL DEFAULT '0',
  `activate` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `activate_key` varchar(32) DEFAULT NULL,
  `profile_name` varchar(50) DEFAULT NULL,
  `profile_sex` enum('man','woman','other') NOT NULL DEFAULT 'other',
  `profile_country` varchar(30) DEFAULT NULL,
  `profile_region` varchar(30) DEFAULT NULL,
  `profile_city` varchar(30) DEFAULT NULL,
  `profile_birthday` datetime DEFAULT NULL,
  `profile_about` text,
  `profile_date` datetime DEFAULT NULL,
  `profile_avatar` varchar(250) DEFAULT NULL,
  `profile_foto` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `login` (`login`),
  UNIQUE KEY `mail` (`mail`),
  KEY `activate_key` (`activate_key`),
  KEY `activate` (`activate`),
  KEY `rating` (`rating`),
  KEY `profile_sex` (`profile_sex`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;